apiVersion: solution.sap/v1
kind: Solution

metadata:
  name: greeting-agent-1be1f
  version: 1.0.0
  description: An AI agent that greets users based on the time of day.

assets:
  - ref: ./assets/greeting-agent/asset.yaml
